/*
 * Köfte
 * Köfte Api V1
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.annotations.SerializedName;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Context
 */
public class ContextTest {
    /**
     * Model tests for Context
     */
    @Test
    public void testContext() {
        // TODO: test Context
    }

}
