/*
 * Köfte
 * Köfte Api V1
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FileUpload
 */
public class FileUploadTest {
    private final FileUpload model = new FileUpload();

    /**
     * Model tests for FileUpload
     */
    @Test
    public void testFileUpload() {
        // TODO: test FileUpload
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'contentType'
     */
    @Test
    public void contentTypeTest() {
        // TODO: test contentType
    }

    /**
     * Test the property 'correlationId'
     */
    @Test
    public void correlationIdTest() {
        // TODO: test correlationId
    }

    /**
     * Test the property 'creationDate'
     */
    @Test
    public void creationDateTest() {
        // TODO: test creationDate
    }

    /**
     * Test the property 'extension'
     */
    @Test
    public void extensionTest() {
        // TODO: test extension
    }

    /**
     * Test the property 'internalName'
     */
    @Test
    public void internalNameTest() {
        // TODO: test internalName
    }

    /**
     * Test the property 'originalFilename'
     */
    @Test
    public void originalFilenameTest() {
        // TODO: test originalFilename
    }

    /**
     * Test the property 'publicResource'
     */
    @Test
    public void publicResourceTest() {
        // TODO: test publicResource
    }

    /**
     * Test the property 'size'
     */
    @Test
    public void sizeTest() {
        // TODO: test size
    }

    /**
     * Test the property 'thumbnailId'
     */
    @Test
    public void thumbnailIdTest() {
        // TODO: test thumbnailId
    }

    /**
     * Test the property 'updatedDate'
     */
    @Test
    public void updatedDateTest() {
        // TODO: test updatedDate
    }

}
